# Generated by Django 4.0.3 on 2022-03-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crypto', '0010_crypto_coingecko_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='abbreviation',
            new_name='symbol',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='coingecko_id',
        ),
        migrations.AlterField(
            model_name='crypto',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
