# Generated by Django 4.0.3 on 2022-03-17 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('crypto', '0011_rename_abbreviation_crypto_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='icon',
        ),
    ]
